version: "3.9"

services:
  db:
    image: postgres:16
    container_name: polyexp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: polyexp
      POSTGRES_PASSWORD: polyexp
      POSTGRES_DB: polyexp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

